### Benchmark Control Plane ###

dataIngestion:
  espbench:
    enabled: true
    # 10000 ns interval = 100,000 msg/sec
    # 1000000 ns interval = 1,000 msg /sec
    sendingInterval: 1000000
    sendingIntervalTimeUnit: NANOSECONDS
    duration: 1
    durationTimeUnit: HOURS

### Data Ingestion (isolated Kafka cluster) ###

kafka:
  podAntiAffinitypreset: hard
  logRetentionHours: 6
  metrics:
    kafka:
      enabled: true
    jmx:
      enabled: true
    serviceMonitor:
      enabled: true
  zookeeper:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

zeppelin:
  enabled: true
  runMode: local
  interpreters:
    - file
    - spark
    - md
    - python
    - sh
  metrics:
    enabled: true
    podMonitor:
      enabled: true
  sparkInterpreter:
    spark:
      master: "spark://sketchbench-espbench-spark-master-svc:7077"
      submit:
        deployMode: "client"
      app:
        name: "zeppelin"
      jar:
        packages: org.apache.spark:spark-sql-kafka-0-10_2.12:3.0.2,org.apache.spark:spark-streaming-kafka-0-10-assembly_2.12:3.0.2
      cores:
        max: 1

### Benchmark Observability Stack ###

kafdrop:
  enabled: true

tobs:
  enabled: false

### System Under Test ###

spark:
  enabled: true
  image:
    repository: sketchbench/bullet-spark-3.0
    tag: "1.0.4"
    pullPolicy: IfNotPresent
  worker:
    replicaCount: 2
    coreLimit: 1
    resources:
      requests:
        memory: "2Gi"
        cpu: "1.5"
      limits:
        memory: "2Gi"
        cpu: "1.5"
  master:
    resources:
      requests:
        memory: "2Gi"
        cpu: "1.5"
      limits:
        memory: "2Gi"
        cpu: "1.5"
  podAntiAffinitypreset: hard
  metrics:
    enabled: true
    podMonitor:
      enabled: true
