image:
  repository: sketchbench/bullet-spark-3.0
  tag: "1.0.4"
  pullPolicy: IfNotPresent
worker:
  replicaCount: 3
  coreLimit: 3
  nodeSelector:
    sketchbench/pool: system-under-test
  resources:
    requests:
      memory: "10Gi"
      cpu: "3.25"
    limits:
      memory: "10Gi"
      cpu: "3.25"
master:
  nodeSelector:
    sketchbench/pool: system-under-test
  resources:
    requests:
      memory: "10Gi"
      cpu: "3.5"
    limits:
      memory: "10Gi"
      cpu: "3.5"
podAntiAffinitypreset: hard
metrics:
  enabled: true
  podMonitor:
    enabled: true
