kube-prometheus-stack:
  alertmanager:
    enabled: false # not needed
  grafana:
    nodeSelector:
      sketchbench/pool: observability
  kube-state-metrics:
    nodeSelector:
      sketchbench/pool: observability
  prometheus:
    prometheusSpec:
      nodeSelector:
        sketchbench/pool: observability
  prometheusOperator:
    admissionWebhooks:
      patch:
        nodeSelector:
          sketchbench/pool: observability
    nodeSelector:
      sketchbench/pool: observability
promscale:
  maintenance:
    nodeSelector:
      sketchbench/pool: observability
  nodeSelector:
    sketchbench/pool: observability
timescaledb-single:
  nodeSelector:
    sketchbench/pool: observability
  # Alternative: https://github.com/timescale/tobs/tree/master/chart#creating-secrets
  unsafe: true
