### Benchmark Control Plane ###

dataIngestion:
  nexmark:
    enabled: true
    nodeSelector:
      sketchbench/pool: benchmark-control-plane

bullet:
  enabled: true
  spark: # System Under Test (isolated Spark cluster)
    enabled: true
    image:
      repository: sketchbench/bullet-spark-3.0
      tag: "1.0.4"
      pullPolicy: IfNotPresent
    worker:
      replicaCount: 3
      coreLimit: 3
      nodeSelector:
        sketchbench/pool: system-under-test
      resources:
        requests:
          memory: "12Gi"
          cpu: "3.5"
        limits:
          memory: "12Gi"
          cpu: "3.5"
    master:
      nodeSelector:
        sketchbench/pool: system-under-test
      resources:
        requests:
          memory: "12Gi"
          cpu: "3.5"
        limits:
          memory: "12Gi"
          cpu: "3.5"
    podAntiAffinitypreset: hard
    metrics:
      enabled: true
      podMonitor:
        enabled: true
  hdfs:
    namenode:
      nodeSelector:
        sketchbench/pool: data-plane
    datanode:
      nodeSelector:
        sketchbench/pool: data-plane
    shell:
      nodeSelector:
        sketchbench/pool: data-plane
  pubsub:
    nodeSelector:
      sketchbench/pool: benchmark-control-plane
    metrics:
      kafka:
        enabled: true
        nodeSelector:
          sketchbench/pool: observability
      jmx:
        enabled: true
      serviceMonitor:
        enabled: true
    zookeeper:
      nodeSelector:
        sketchbench/pool: data-plane
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
  pubsubMonit:
    deployment:
      nodeSelector:
        sketchbench/pool: observability
  ui:
    nodeSelector:
      sketchbench/pool: benchmark-control-plane
  webservice:
    nodeSelector:
      sketchbench/pool: benchmark-control-plane
  sparkBackend:
    executorCores: 3
    executorMemory: 10G
    nodeSelector:
      sketchbench/pool: benchmark-control-plane
    image:
      repository: sketchbench/bullet-spark-3.0
    hdfsUser: hadoop
    hdfs:
      port: 8020
    metrics:
      enabled: true
      podMonitor:
        enable: true
    config:
      bullet:
        spark:
          dsl:
            data:
              producer:
                enable: true
            deserializer:
              enable: false
        dsl:
          connector:
            class:
              name: com.yahoo.bullet.dsl.connector.KafkaConnector
            kafka:
              topics:
                - SketchBench-nexmark
              bootstrap:
                servers:
                  - kafka:9092
          converter:
            class:
              name: com.yahoo.bullet.dsl.converter.JSONBulletRecordConverter
            schema:
              type:
                check:
                  enable: false
          deserializer:
            class:
              name: com.yahoo.bullet.dsl.deserializer.IdentityDeserializer
    dsl:
      schema: |
        {
          "fields": [
            {
              "name": "iij_timestamp",
              "reference": "event.iij_timestamp",
              "type": "LONG"
            },
            {
              "name": "auction_id",
              "reference": "event.auction_id",
              "type": "INTEGER"
            },
            {
              "name": "partition_id",
              "reference": "event.partition_id",
              "type": "INTEGER"
            },
            {
              "name": "time",
              "reference": "event.time",
              "type": "LONG"
            },
            {
              "name": "person",
              "reference": "event.person",
              "type": "INTEGER"
            },
            {
              "name": "bid",
              "reference": "event.bid",
              "type": "INTEGER"
            }
          ]
        }

zeppelin:
  enabled: true
  nodeSelector:
    sketchbench/pool: benchmark-control-plane
  runMode: local
  interpreters:
    - file
    - spark
    - md
    - python
  metrics:
    enabled: true
    podMonitor:
      enabled: true
  sparkInterpreter:
    spark:
      master: "spark://sketchbench-nexmark-spark-master-svc:7077"
      submit:
        deployMode: "client"
      app:
        name: "zeppelin"
      jar:
        packages: org.apache.spark:spark-sql-kafka-0-10_2.12:3.0.2,org.apache.spark:spark-streaming-kafka-0-10-assembly_2.12:3.0.2
      cores:
        max: 1

### Benchmark Observability Stack ###

kafdrop:
  enabled: true
  deployment:
    nodeSelector:
      sketchbench/pool: observability

### Data Ingestion (isolated Kafka cluster) ###

kafka:
  nodeSelector:
    sketchbench/pool: data-ingestion
  podAntiAffinitypreset: hard
  logRetentionHours: 6
  resources:
    requests:
      memory: "5Gi"
      cpu: "1.5"
    limits:
      memory: "5Gi"
      cpu: "1.5"
  metrics:
    kafka:
      enabled: true
      nodeSelector:
        sketchbench/pool: observability
    jmx:
      enabled: true
    serviceMonitor:
      enabled: true
  zookeeper:
    nodeSelector:
      sketchbench/pool: data-plane
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
