### Benchmark Control Plane ###

dataIngestion:
  tester:
    enabled: true
    nodeSelector:
      sketchbench/pool: control-plane

bullet:
  enabled: true
  spark:
    # Use SketchBench-managed Spark instance in separate node pool
    enabled: false
  hdfs:
    namenode:
      nodeSelector:
        sketchbench/pool: data-plane
    datanode:
      nodeSelector:
        sketchbench/pool: data-plane
    shell:
      nodeSelector:
        sketchbench/pool: data-plane
  pubsub:
    nodeSelector:
      sketchbench/pool: control-plane
    zookeeper:
      nodeSelector:
        sketchbench/pool: data-plane
  pubsubMonit:
    nodeSelector:
      sketchbench/pool: observability
  ui:
    nodeSelector:
      sketchbench/pool: control-plane
  webservice:
    nodeSelector:
      sketchbench/pool: control-plane
  sparkBackend:
    nodeSelector:
      sketchbench/pool: system-under-test
    image:
      repository: sketchbench/bullet-spark-3.0
    hdfsUser: hadoop
    hdfs:
      port: 8020
    config:
      bullet:
        spark:
          dsl:
            data:
              producer:
                enable: true
            deserializer:
              enable: false
        dsl:
          connector:
            class:
              name: com.yahoo.bullet.dsl.connector.KafkaConnector
            kafka:
              topics:
                - SketchBench-1-1
              bootstrap:
                servers:
                  - kafka:9092
          converter:
            class:
              name: com.yahoo.bullet.dsl.converter.JSONBulletRecordConverter
            schema:
              type:
                check:
                  enable: false
          deserializer:
            class:
              name: com.yahoo.bullet.dsl.deserializer.IdentityDeserializer
    dsl:
      schema: |
        {
          "fields": [
            {
              "name": "SketchBenchMessageID",
              "type": "INTEGER"
            },
            {
              "name": "SketchBenchBoolean",
              "type": "BOOLEAN"
            },
            {
              "name": "SketchBenchInteger",
              "type": "INTEGER"
            },
            {
              "name": "SketchBenchLong",
              "type": "LONG"
            },
            {
              "name": "SketchBenchFloat",
              "type": "FLOAT"
            },
            {
              "name": "SketchBenchDouble",
              "type": "DOUBLE"
            },
            {
              "name": "SketchBenchString",
              "type": "STRING"
            },
            {
              "name": "SketchBenchBooleanMap",
              "type": "BOOLEAN_MAP"
            },
            {
              "name": "SketchBenchIntegerMap",
              "type": "INTEGER_MAP"
            },
            {
              "name": "SketchBenchLongMap",
              "type": "LONG_MAP"
            },
            {
              "name": "SketchBenchFloatMap",
              "type": "FLOAT_MAP"
            },
            {
              "name": "SketchBenchDoubleMap",
              "type": "DOUBLE_MAP"
            },
            {
              "name": "SketchBenchStringMap",
              "type": "STRING_MAP"
            },
            {
              "name": "SketchBenchBooleanMapMap",
              "type": "BOOLEAN_MAP_MAP"
            },
            {
              "name": "SketchBenchIntegerMapMap",
              "type": "INTEGER_MAP_MAP"
            },
            {
              "name": "SketchBenchLongMapMap",
              "type": "LONG_MAP_MAP"
            },
            {
              "name": "SketchBenchFloatMapMap",
              "type": "FLOAT_MAP_MAP"
            },
            {
              "name": "SketchBenchDoubleMapMap",
              "type": "DOUBLE_MAP_MAP"
            },
            {
              "name": "SketchBenchStringMapMap",
              "type": "STRING_MAP_MAP"
            },
            {
              "name": "SketchBenchBooleanList",
              "type": "BOOLEAN_LIST"
            },
            {
              "name": "SketchBenchIntegerList",
              "type": "INTEGER_LIST"
            },
            {
              "name": "SketchBenchLongList",
              "type": "LONG_LIST"
            },
            {
              "name": "SketchBenchFloatList",
              "type": "FLOAT_LIST"
            },
            {
              "name": "SketchBenchDoubleList",
              "type": "DOUBLE_LIST"
            },
            {
              "name": "SketchBenchStringList",
              "type": "STRING_LIST"
            },
            {
              "name": "SketchBenchBooleanMapList",
              "type": "BOOLEAN_MAP_LIST"
            },
            {
              "name": "SketchBenchIntegerMapList",
              "type": "INTEGER_MAP_LIST"
            },
            {
              "name": "SketchBenchLongMapList",
              "type": "LONG_MAP_LIST"
            },
            {
              "name": "SketchBenchFloatMapList",
              "type": "FLOAT_MAP_LIST"
            },
            {
              "name": "SketchBenchDoubleMapList",
              "type": "DOUBLE_MAP_LIST"
            },
            {
              "name": "SketchBenchStringMapList",
              "type": "STRING_MAP_LIST"
            }
          ]
        }

zeppelin:
  enabled: true
  deployment:
    nodeSelector:
      sketchbench/pool: control-plane
  runMode: local
  interpreters:
    - file
    - spark
    - md
    - python
    - livy
    - sparql
  sparkInterpreter:
    spark:
      master: "spark://my-sketchbench-spark-master-svc:7077"
      submit:
        deployMode: "client"
      app:
        name: "zeppelin"

### Benchmark Observability Stack ###

tobs:
  enabled: true
  kube-prometheus-stack:
    alertmanager:
      alertmanagerSpec:
        nodeSelector:
          sketchbench/pool: observability
    grafana:
      nodeSelector:
        sketchbench/pool: observability
    kube-state-metrics:
      nodeSelector:
        sketchbench/pool: observability
    prometheus:
      prometheusSpec:
        nodeSelector:
          sketchbench/pool: observability
    prometheusOperator:
      admissionWebhooks:
        patch:
          nodeSelector:
            sketchbench/pool: observability
      nodeSelector:
        sketchbench/pool: observability
  promscale:
    maintenance:
      nodeSelector:
        sketchbench/pool: observability
    nodeSelector:
      sketchbench/pool: observability
  timescaledb-single:
    nodeSelector:
      sketchbench/pool: observability

kafdrop:
  enabled: true
  deployment:
    nodeSelector:
      sketchbench/pool: observability

### Data Ingestion (isolated Kafka cluster) ###

kafka:
  nodeSelector:
    sketchbench/pool: data-ingestion
  podAntiAffinitypreset: hard
  zookeeper:
    nodeSelector:
      sketchbench/pool: data-ingestion

### System Under Test (isolated Spark cluster) ###

spark:
  enabled: true
  image:
    repository: sketchbench/bullet-spark-3.0
    tag: "1.0.4"
    pullPolicy: IfNotPresent
  worker:
    replicaCount: 3
    nodeSelector:
      sketchbench/pool: system-under-test
  master:
    nodeSelector:
      sketchbench/pool: system-under-test
  podAntiAffinitypreset: hard

hdfs:
  namenode:
    nodeSelector:
      sketchbench/pool: system-under-test
  datanode:
    nodeSelector:
      sketchbench/pool: system-under-test
