### Benchmark Control Plane ###

dataIngestion:
  nexmark:
    enabled: true
    nodeSelector:
      sketchbench/pool: control-plane

### Benchmark Observability Stack ###

kafdrop:
  enabled: true
  deployment:
    nodeSelector:
      sketchbench/pool: observability

### Data Ingestion (isolated Kafka cluster) ###

kafka:
  nodeSelector:
    sketchbench/pool: data-ingestion
  podAntiAffinitypreset: hard
  logRetentionHours: 6
  resources:
    requests:
      memory: "5Gi"
      cpu: "1.5"
    limits:
      memory: "5Gi"
      cpu: "1.5"
  metrics:
    kafka:
      enabled: true
      nodeSelector:
        sketchbench/pool: observability
    jmx:
      enabled: true
    serviceMonitor:
      enabled: true
  zookeeper:
    nodeSelector:
      sketchbench/pool: data-plane
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

zeppelin:
  enabled: false
