{
 "title": "SketchBench",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "broker",
    "label": "Kafka Broker",
    "query": {
     "query": "label_values(kafka_topic_partitions{app_kubernetes_io_name=\"kafka\",topic!=\"__consumer_offsets\"}, app_kubernetes_io_instance)"
    }
   },
   {
    "name": "topic",
    "label": "Kafka Topic",
    "query": {
     "query": "label_values(kafka_topic_partitions{app_kubernetes_io_name=\"kafka\",app_kubernetes_io_instance=\"$broker\",topic!=\"__consumer_offsets\"}, topic)"
    }
   },
   {
    "name": "sparkapp",
    "label": "Spark App Name",
    "query": {
     "query": "label_values(metrics_executor_rddBlocks, application_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bytes in/out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesinpersec_count{app_kubernetes_io_instance=\"$broker\", topic=~\"$topic\"}[5m])) by (topic)",
     "legendFormat": "Bytes in (MB)"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesoutpersec_count{app_kubernetes_io_instance=\"$broker\", topic=~\"$topic\"}[5m])) by (topic)",
     "legendFormat": "Bytes out (MB)"
    }
   ]
  },
  {
   "title": "Requests in/out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_totalproducerequestspersec_count{app_kubernetes_io_instance=\"$broker\", topic=~\"$topic\"}[5m])) by (topic)",
     "legendFormat": "Produce Requests"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_totalfetchrequestspersec_count{app_kubernetes_io_instance=\"$broker\", topic=~\"$topic\"}[5m])) by (topic)",
     "legendFormat": "Fetch Requests"
    }
   ]
  },
  {
   "title": "Approximate Lag by Consumer Group",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroup_lag{topic=~\"$topic\", job=\"sketchbench-espbench-kafka-metrics\"}",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Current Offset",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{app_kubernetes_io_instance=\"$broker\", topic=~\"$topic\"}[5m])) by (topic)",
     "legendFormat": "Current Partition Offset"
    },
    {
     "expr": "sum(rate(kafka_consumergroup_current_offset{app_kubernetes_io_instance=\"$broker\", topic=~\"$topic\"}[5m])) by (topic)",
     "legendFormat": "Current Consumer Offset"
    }
   ]
  },
  { "title": "Spark", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Spark Worker CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{container=\"spark-worker\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Spark Driver CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{container=\"spark-backend\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Spark Worker Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=\"spark-worker\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Spark Driver Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=\"spark-backend\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RDD Blocks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_executor_rddBlocks{executor_id!=\"driver\", application_name=\"$sparkapp\"}",
     "legendFormat": "Executor {{executor_id}}"
    }
   ]
  },
  {
   "title": "Rate of Completed Tasks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(metrics_executor_completedTasks_total{executor_id!=\"driver\", application_name=\"$sparkapp\"}[1m])",
     "legendFormat": "Executor {{executor_id}}"
    }
   ]
  },
  {
   "title": "Active Tasks",
   "type": "graph",
   "description": "Number of tasks currently executing.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(metrics_executor_activeTasks{executor_id!=\"driver\", application_name=\"$sparkapp\"}) by (executor_id)",
     "legendFormat": "Executor {{executor_id}}"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_totalCores{executor_id!=\"driver\", application_name=\"$sparkapp\"}) by (executor_id)",
     "legendFormat": "Executor {{executor_id}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "description": "Memory used for storage of data like RDD partitions cached in memory.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(metrics_executor_memoryUsed_bytes{executor_id!=\"driver\", application_name=\"$sparkapp\"}) by (executor_id)",
     "legendFormat": "Executor {{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Read/Write",
   "type": "graph",
   "description": "Total shuffle bytes and records read/written.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(metrics_executor_totalShuffleRead_bytes_total{executor_id!=\"driver\", application_name=\"$sparkapp\"}) by (executor_id)",
     "legendFormat": "Executor {{executor_id}} Shuffle Read"
    },
    {
     "expr": "sum(metrics_executor_totalShuffleWrite_bytes_total{executor_id!=\"driver\", application_name=\"$sparkapp\"}) by (executor_id)",
     "legendFormat": "Executor {{executor_id}} Shuffle Write"
    }
   ]
  }
 ]
}